version: '3'
services:
  joke-api:
    image: joke-api:0.2.0
    build:
      context: ./src/api
      dockerfile: Dockerfile
    volumes:
      - ./src/api/templates:/app/templates
    ports:
      - 5000:5000
  db:
    image: postgres:11
    env_file:
      - config/env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - config/env-pgadmin.env
    ports:
      - '5555:5555'
volumes:
  app-db-data:
