version: '3'
services:
  joke-telegram:
    image: joke-telegram:0.4.0
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - joke-flask
  joke-flask:
    image: joke-flask:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5050:5050"
