version: '3'
services:
  joke-telegram:
    image: joke-telegram:0.5.1
    build:
      context: ./src/bot/
      dockerfile: Dockerfile
    links:
      - joke-api
  joke-api:
    image: joke-api:0.2.0
    build:
      context: ./src/api
      dockerfile: Dockerfile
    volumes:
      - ./src/api/templates:/app/templates
    ports:
      - 5000:5000
