version: '3'
services:
  joke-telegram:
    image: joke-telegram:0.5.0
    build:
      context: ./src/bot/
      dockerfile: Dockerfile
    links:
      - joke-api
  joke-api:
    image: joke-api:0.1.0
    build:
      context: ./src/api
      dockerfile: Dockerfile
    volumes:
      - ./src/api/templates:/app/templates
      - ./src/api/.well-known:/app/.well-known
      - ./src/api/cert:/app/cert
  nginx-reverse-proxy:
    image: nginx-reverse-proxy:0.0.1
    ports:
      - 80:80
      - 443:443
    restart: always
    build:
      context: ./src/api/nginx
    volumes:
      - ./conf:/etc/nginx
    links:
      - joke-api
