version: '3'
services:
  joke-telegram:
    image: joke-telegram:0.5.0
    build:
      context: ./src/bot/
      dockerfile: Dockerfile
    links:
      - joke-api
  joke-api:
    image: joke-api:0.0.1
    volumes:
      - /etc/letsencrypt/live/watxaut.com:/etc
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "80:80"
